// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMB7nTzyj5FQYKb4LhthjWsQ3UHDipE7U',
    appId: '1:714613150281:web:061e676cff62f879a6a598',
    messagingSenderId: '714613150281',
    projectId: 'marathon1-842bc',
    authDomain: 'marathon1-842bc.firebaseapp.com',
    storageBucket: 'marathon1-842bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJN2I52bIWQ-1rH_FzdyIuaE9cYJSoiQ',
    appId: '1:714613150281:android:60943061e62feca7a6a598',
    messagingSenderId: '714613150281',
    projectId: 'marathon1-842bc',
    storageBucket: 'marathon1-842bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO6qHgmDiD-5F5msLeHWBQTxBHN2PagIs',
    appId: '1:714613150281:ios:6af6f21e5605d551a6a598',
    messagingSenderId: '714613150281',
    projectId: 'marathon1-842bc',
    storageBucket: 'marathon1-842bc.firebasestorage.app',
    iosBundleId: 'com.example.og',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO6qHgmDiD-5F5msLeHWBQTxBHN2PagIs',
    appId: '1:714613150281:ios:6af6f21e5605d551a6a598',
    messagingSenderId: '714613150281',
    projectId: 'marathon1-842bc',
    storageBucket: 'marathon1-842bc.firebasestorage.app',
    iosBundleId: 'com.example.og',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMB7nTzyj5FQYKb4LhthjWsQ3UHDipE7U',
    appId: '1:714613150281:web:af1db7efe145bc14a6a598',
    messagingSenderId: '714613150281',
    projectId: 'marathon1-842bc',
    authDomain: 'marathon1-842bc.firebaseapp.com',
    storageBucket: 'marathon1-842bc.firebasestorage.app',
  );
}
